require("plugins")
require("config")
require("keybindings")
require("lualine-nvim")
require("lsp_ui")
require("lsp")
require("filetree")
require("treesitter")
require("telescope_config")
-- require("trouble_config")
require("terminal")
require("gitsigns_config")
require("autopairs")
-- require("tabs")
require("completions")
require("formatters")
require("colorizer_config")
require("selection_highlight")
-- require("cmdline_ui")
require("dashboard_config")
require("whichKey")
require("diff")

-- vim.opt.foldmethod = "expr"
-- vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
